steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image-name', '.']

options:
  logging: CLOUD_LOGGING_ONLY  # ログはCloud Loggingに送られる

timeout: '1200s'

images:
  - 'gcr.io/$PROJECT_ID/your-image-name'
