services:
  - type: web
    name: pixiv-searcher
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
